name: "Task"
description: "Crie uma tarefa tecnica ou organizacional."
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Use este formulario para tarefas internas.
  - type: textarea
    id: objetivo
    attributes:
      label: "Objetivo"
      description: "Descreva o que deve ser entregue."
    validations:
      required: true
  - type: textarea
    id: escopo
    attributes:
      label: "Escopo"
      description: "O que esta incluso e o que esta fora."
    validations:
      required: false
  - type: textarea
    id: criterios
    attributes:
      label: "Criterios de aceite"
      description: "Como sabemos que esta pronto?"
      placeholder: "- ...\n- ..."
    validations:
      required: true
  - type: input
    id: prazo
    attributes:
      label: "Prazo (opcional)"
      placeholder: "Ex.: 2026-02-15"
    validations:
      required: false
